export const SPINNER_VERBS: string[] = [
  "完成中", // Accomplishing
  "行动中", // Actioning
  "实现中", // Actualizing
  "架构中", // Architecting
  "烘焙中", // Baking
  "传送中", // Beaming
  "嗞嗞中", // Beboppin'
  "迷惑中", // Befuddling
  "翻涌中", // Billowing
  "焯水中", // Blanching
  "侃侃中", // Bloviating
  "摇摆中", // Boogieing
  "搞搞中", // Boondoggling
  "戳戳中", // Booping
  "启动中", // Bootstrapping
  "酝酿中", // Brewing
  "包馒头中", // Bunning
  "钻洞中", // Burrowing
  "计算中", // Calculating
  "腻歪中", // Canoodling
  "焦糖化中", // Caramelizing
  "级联中", // Cascading
  "弹射中", // Catapulting
  "脑洞中", // Cerebrating
  "引导中", // Channeling
  "频道中", // Channelling
  "编舞中", // Choreographing
  "搅动中", // Churning
  "Claude中", // Clauding
  "融合中", // Coalescing
  "沉思中", // Cogitating
  "组合中", // Combobulating
  "谱曲中", // Composing
  "运算中", // Computing
  "炮制中", // Concocting
  "考量中", // Considering
  "冥想中", // Contemplating
  "烹饪中", // Cooking
  "精制中", // Crafting
  "创造中", // Creating
  "咀嚼中", // Crunching
  "结晶中", // Crystallizing
  "培育中", // Cultivating
  "解码中", // Deciphering
  "审议中", // Deliberating
  "决策中", // Determining
  "磨蹭中", // Dilly-dallying
  "捣乱中", // Discombobulating
  "干活中", // Doing
  "涂鸦中", // Doodling
  "淋淋中", // Drizzling
  "退潮中", // Ebbing
  "施效中", // Effecting
  "阐明中", // Elucidating
  "润色中", // Embellishing
  "施魔中", // Enchanting
  "畅想中", // Envisioning
  "蒸发中", // Evaporating
  "发酵中", // Fermenting
  "磨叽中", // Fiddle-faddling
  "操弄中", // Finagling
  "火焰中", // Flambéing
  "叽叽喳喳中", // Flibbertigibbeting
  "流淌中", // Flowing
  "搞晕中", // Flummoxing
  "扑棱中", // Fluttering
  "锻造中", // Forging
  "塑形中", // Forming
  "嬉戏中", // Frolicking
  "裹霜中", // Frosting
  "闲逛中", // Gallivanting
  "狂奔中", // Galloping
  "装饰中", // Garnishing
  "生成中", // Generating
  "比划中", // Gesticulating
  "萌芽中", // Germinating
  "Git化中", // Gitifying
  "律动中", // Grooving
  "呼啸中", // Gusting
  "和谐中", // Harmonizing
  "哈希中", // Hashing
  "孵化中", // Hatching
  "放牧中", // Herding
  "嗡嗡中", // Honking
  "喧嚣中", // Hullaballooing
  "超空间中", // Hyperspacing
  "灵感中", // Ideating
  "想象中", // Imagining
  "即兴中", // Improvising
  "温育中", // Incubating
  "推断中", // Inferring
  "注入中", // Infusing
  "电离中", // Ionizing
  "抖腿中", // Jitterbugging
  "切丝中", // Julienning
  "揉面中", // Kneading
  "发面中", // Leavening
  "漂浮中", // Levitating
  "耗时中", // Lollygagging
  "显化中", // Manifesting
  "腌制中", // Marinating
  "漫游中", // Meandering
  "变形中", // Metamorphosing
  "薄雾中", // Misting
  "月步中", // Moonwalking
  "溜达中", // Moseying
  "琢磨中", // Mulling
  "集结中", // Mustering
  "思量中", // Musing
  "雾化中", // Nebulizing
  "筑巢中", // Nesting
  "报纸中", // Newspapering
  "面条中", // Noodling
  "成核中", // Nucleating
  "环绕中", // Orbiting
  "统筹中", // Orchestrating
  "渗透中", // Osmosing
  "散步中", // Perambulating
  "渗滤中", // Percolating
  "浏览中", // Perusing
  "哲思中", // Philosophising
  "光合中", // Photosynthesizing
  "授粉中", // Pollinating
  "沉吟中", // Pondering
  "高谈中", // Pontificating
  "扑腾中", // Pouncing
  "沉淀中", // Precipitating
  "变戏法中", // Prestidigitating
  "处理中", // Processing
  "校对中", // Proofing
  "传播中", // Propagating
  "捯饬中", // Puttering
  "迷思中", // Puzzling
  "量子化中", // Quantumizing
  "炫耀中", // Razzle-dazzling
  "花里胡哨中", // Razzmatazzing
  "重新组合中", // Recombobulating
  "网格中", // Reticulating
  "栖息中", // Roosting
  "反刍中", // Ruminating
  "嫩煎中", // Sautéing
  "蹦跳中", // Scampering
  "拖行中", // Schlepping
  "疾驰中", // Scurrying
  "调味中", // Seasoning
  "捣鬼中", // Shenaniganing
  "扭动中", // Shimmying
  "慢炖中", // Simmering
  "溜走中", // Skedaddling
  "素描中", // Sketching
  "蜿蜒中", // Slithering
  "揉捏中", // Smooshing
  "蹦迪中", // Sock-hopping
  "探洞中", // Spelunking
  "旋转中", // Spinning
  "萌发中", // Sprouting
  "炖煮中", // Stewing
  "升华中", // Sublimating
  "旋涡中", // Swirling
  "俯冲中", // Swooping
  "共生中", // Symbioting
  "合成中", // Synthesizing
  "回火中", // Tempering
  "思考中", // Thinking
  "雷鸣中", // Thundering
  "摆弄中", // Tinkering
  "瞎折腾中", // Tomfoolering
  "颠倒中", // Topsy-turvying
  "变身中", // Transfiguring
  "蜕变中", // Transmuting
  "扭转中", // Twisting
  "波动中", // Undulating
  "展开中", // Unfurling
  "解开中", // Unravelling
  "振动中", // Vibing
  "摇摆摇摆中", // Waddling
  "漂泊中", // Wandering
  "扭曲中", // Warping
  "叫啥来着中", // Whatchamacalliting
  "漩涡中", // Whirlpooling
  "嗡鸣中", // Whirring
  "搅拌中", // Whisking
  "晃悠中", // Wibbling
  "工作中", // Working
  "驯服中", // Wrangling
  "提鲜中", // Zesting
  "曲折中", // Zigzagging
];

export function getRandomVerb(): string {
  return SPINNER_VERBS[Math.floor(Math.random() * SPINNER_VERBS.length)];
}
